CREATE DATABASE BTQLBANHANG
USE BTQLBANHANG

CREATE TABLE KHACHHANG
(
	MAKHACHHANG VARCHAR(10) PRIMARY KEY,
	TENCONGTY NVARCHAR(50) NOT NULL,
	TENGIAODICH NVARCHAR(100) NOT NULL,
	DIACHI NVARCHAR(100),
	EMAIL VARCHAR(50),
	DIENTHOAI VARCHAR(15) NOT NULL,
	FAX VARCHAR(15)
)

EXEC SP_RENAME 'KHACHHANG.TENCONGTY', 'TENKHACHHANG'
CREATE TABLE NHANVIEN
(	
	MANHANVIEN VARCHAR(10) PRIMARY KEY,
	HO NVARCHAR(20) NOT NULL,
	TEN NVARCHAR(20) NOT NULL,
	NGAYSINH DATE NOT NULL,
	NGAYLAMVIEC DATE NOT NULL,
	DIACHI NVARCHAR(70) NOT NULL,
	DIENTHOAI VARCHAR(15) NOT NULL,
	LUONGCOBAN FLOAT NOT NULL,
	PHUCAP FLOAT NOT NULL
)
CREATE TABLE DONDATHANG
(
	SOHOADON INT IDENTITY PRIMARY KEY,
	MAKHACHHANG VARCHAR(10) FOREIGN KEY(MAKHACHHANG) REFERENCES KHACHHANG(MAKHACHHANG),
	MANHANVIEN VARCHAR(10) FOREIGN KEY(MANHANVIEN) REFERENCES NHANVIEN(MANHANVIEN),
	NGAYDATHANG DATE NOT NULL,
	NGAYGIAOHANG DATE NOT NULL,
	NGAYCHUYENHANG DATE NOT NULL,
	NOIGIAOHANG NVARCHAR(70) NOT NULL
)


CREATE TABLE NHACUNGCAP
(
	MACONGTY VARCHAR(10) PRIMARY KEY,
	TENCONGTY NVARCHAR(50) NOT NULL,
	TENGIAODICH NVARCHAR(100) NOT NULL,
	DIACHI NVARCHAR(100),	
	DIENTHOAI VARCHAR(15) NOT NULL,
	FAX VARCHAR(15),
	EMAIL VARCHAR(50)
)

CREATE TABLE LOAIHANG
(
	MALOAIHANG VARCHAR(10) PRIMARY KEY,
	TENLOAIHANG NVARCHAR(50) NOT NULL
)
-- XÓA DỮ LIỆU TRONG BẢNG
--DELETE FROM LOAIHANG

CREATE TABLE MATHANG
(
	MAHANG VARCHAR(10) PRIMARY KEY,
	TENHANG NVARCHAR(50) NOT NULL,
	MACONGTY VARCHAR(10) FOREIGN KEY(MACONGTY) REFERENCES NHACUNGCAP(MACONGTY),
	MALOAIHANG VARCHAR(10)FOREIGN KEY(MALOAIHANG) REFERENCES LOAIHANG(MALOAIHANG),
	SOLUONG INT NOT NULL,
	DONVITINH NVARCHAR(20) NOT NULL,
	GIAHANG FLOAT NOT NULL,
)

CREATE TABLE CHITIETDATHANG
(
	SOHOADON INT FOREIGN KEY(SOHOADON) REFERENCES DONDATHANG(SOHOADON),
	MAHANG VARCHAR(10)FOREIGN KEY(MAHANG) REFERENCES MATHANG(MAHANG),
	GIABAN FLOAT NOT NULL,
	SOLUONG INT NOT NULL,
	MUCGIAMGIA FLOAT NOT NULL,
	PRIMARY KEY(SOHOADON,MAHANG)	
)

-- CAU1:1.	Bổ sung ràng buộc thiết lập giá trị mặc định bằng 1 cho cột SOLUONG và bằng 0 cho cột MUCGIAMGIA trong bảng CHITIETDATHANG 
ALTER TABLE CHITIETDATHANG ADD  DEFAULT(1) FOR SOLUONG;
ALTER TABLE CHITIETDATHANG ADD  DEFAULT(0) FOR MUCGIAMGIA;
-- CAU2:2.	Bổ sung cho bảng DONDATHANG ràng buộc kiểm tra ngày giao hàng và ngày chuyển hàng phải sau hoặc bằng với ngày đặt hàng. 
ALTER TABLE DONDATHANG ADD CHECK (NGAYCHUYENHANG >= NGAYDATHANG AND  NGAYGIAOHANG >= NGAYCHUYENHANG);
--CAU3:3.	Bổ sung ràng buộc cho bảng NHANVIEN để đảm bảo rằng một nhân viên chỉ có thể làm việc trong công ty khi đủ 18 tuổi và không quá 60 tuổi. 
ALTER TABLE NHANVIEN ADD CHECK(DATEDIFF(YY,NGAYSINH,NGAYLAMVIEC) BETWEEN 18 AND 60);
-- CAU4:4.	Cho biết danh sách các đối tác cung cấp hàng cho công ty.
SELECT * FROM NHACUNGCAP ;
--CAU5:5.	Mã hàng, tên hàng và số lượng của các mặt hàng hiện có trong công 
SELECT MAHANG,TENHANG,SOLUONG FROM MATHANG;
--CAU6:6.	Họ tên và địa chỉ và năm bắt đầu làm việc của các nhân viên trong công ty
SELECT * FROM NHANVIEN WHERE MANHANVIEN='NV100';
--CAU7:7.	Địa chỉ và điện thoại của nhà cung cấp có tên giao dịch VINAMILK là gì?
SELECT DIACHI,DIENTHOAI,TENCONGTY FROM NHACUNGCAP WHERE TENGIAODICH LIKE N'%VINAMILK%';
--CAU8:8.	Cho biết mã và tên của các mặt hàng có giá lớn hơn 100000 và số lượng hiện có ít hơn 50 
SELECT MAHANG,TENHANG FROM MATHANG WHERE GIAHANG>200000 AND SOLUONG>100;
--CAU9:9.	Cho biết mỗi mặt hàng trong công ty do ai cung cấp 
SELECT TENHANG,TENCONGTY FROM MATHANG,NHACUNGCAP WHERE MATHANG.MACONGTY = NHACUNGCAP.MACONGTY;
--CAU10:10.	Công ty Việt Tiến có nhưng mặt hàng nào?
SELECT TENHANG FROM  MATHANG,(SELECT MACONGTY FROM NHACUNGCAP WHERE TENCONGTY LIKE N'VIỆT TIẾN') AS MCT WHERE  MCT.MACONGTY =MATHANG.MACONGTY;
--CAU11:	Loại hàng thực phẩm do những công ty nào cung cấp đó là gì? 
SELECT NCC.TENCONGTY FROM NHACUNGCAP NCC JOIN
dbo.MATHANG MH ON	MH.MACONGTY = NCC.MACONGTY JOIN
dbo.LOAIHANG LH ON	LH.MALOAIHANG = MH.MALOAIHANG
WHERE LH.TENLOAIHANG LIKE N'%ĐỒ UỐNG%'
GO

-- LUYỆN TẬP HÀM:

ALTER FUNCTION FN_SOLUONGNV
(
	@NAMSINH date , 
	@LUONGCOBAN DECIMAL
) 
RETURNS INT
AS
BEGIN
	DECLARE @SOLUONGNV INT=0;
	SELECT @SOLUONGNV= COUNT(*) FROM dbo.NHANVIEN WHERE DATEPART(YEAR,NGAYSINH) >DATEPART(YEAR,@NAMSINH) AND LUONGCOBAN>@LUONGCOBAN
	RETURN @SOLUONGNV
END
GO

SELECT dbo.FN_SOLUONGNV ('20190909', 20000)


--- CÂU 12:.	Những khách hàng nào (tên giao dịch) đã đặt mua mặt hàng Sữa hộp XYZ của công ty?
SELECT	KH.TENKHACHHANG FROM dbo.KHACHHANG KH JOIN dbo.DONDATHANG DDH ON DDH.MAKHACHHANG = KH.MAKHACHHANG
JOIN dbo.CHITIETDATHANG CTDH ON CTDH.SOHOADON = DDH.SOHOADON
JOIN dbo.MATHANG MH ON MH.MAHANG = CTDH.MAHANG
JOIN dbo.NHACUNGCAP NCC ON NCC.MACONGTY = MH.MACONGTY
WHERE MH.TENHANG LIKE N'SỮA TƯƠI' AND NCC.TENCONGTY LIKE N'VIỆT TIẾN';

--- CÂU 13:	Đơn đặt hàng số 1 do ai đặt và do nhân viên nào lập, thời gian và địa điểm giao hàng là ở đâu?
SELECT KH.TENKHACHHANG,NV.TEN,DDH.NGAYGIAOHANG,DDH.NOIGIAOHANG FROM dbo.DONDATHANG DDH 
JOIN dbo.NHANVIEN NV ON NV.MANHANVIEN = DDH.MANHANVIEN
JOIN dbo.KHACHHANG KH ON KH.MAKHACHHANG = DDH.MAKHACHHANG
WHERE DDH.SOHOADON =1;

--- CÂU 14:	Hãy cho biết số tiền lương mà công ty phải trả cho mỗi nhân viên là bao nhiêu (lương = lương cơ bản + phụ cấp)

SELECT LƯƠNG = LUONGCOBAN + PHUCAP FROM dbo.NHANVIEN ;

-- CÂU 15:15.	Trong đơn đặt hàng số 3 đặt mua những mặt hàng nào và số tiền mà khách hàng phải trả cho mỗi mặt hàng là bao nhiêu
-- SOLUONG×GIABAN – SOLUONG×GIABAN×MUCGIAMGIA/100) 

SELECT MH.TENHANG,TIỀN= CTDH.GIABAN * CTDH.SOLUONG - MUCGIAMGIA FROM dbo.MATHANG AS MH,dbo.CHITIETDATHANG AS CTDH 
WHERE CTDH.SOHOADON = 4 AND CTDH.MAHANG = MH.MAHANG

-- CÂU 16: Cho biết tên công ty, tên giao dch, địa chỉ và điện thoại của các khách hàng và các nhà cung cấp hàng cho công ty. 
SELECT TENKHACHHANG,TENGIAODICH,DIACHI,DIENTHOAI FROM dbo.KHACHHANG
UNION ALL
SELECT TENCONGTY,TENGIAODICH,DIACHI,DIENTHOAI FROM dbo.NHACUNGCAP

-- CÂU 17: 17.	Trong công ty có những nhân viên nào có cùng ngày sinh? 

SELECT nv1.HO,nv1.TEN,nv1.NGAYSINH FROM dbo.NHANVIEN nv1 JOIN dbo.NHANVIEN nv2 
ON nv2.NGAYSINH = nv1.NGAYSINH AND nv2.MANHANVIEN <> nv1.MANHANVIEN

-- CÂU 18:Những mặt hàng nào chưa từng được khách hàng đặt mua?

SELECT	MH.TENHANG FROM dbo.MATHANG MH 
WHERE NOT EXISTS(SELECT CTDH.MAHANG FROM dbo.CHITIETDATHANG CTDH WHERE CTDH.MAHANG = MH.MAHANG);

-- CÂU 19:Những nhân viên nào của công ty chưa từng lập bất kỳ một hoá đơn đặt hàng nào? 

SELECT NV.HO, NV.TEN FROM dbo.NHANVIEN NV 
WHERE NOT EXISTS(SELECT DDH.MANHANVIEN FROM dbo.DONDATHANG DDH WHERE DDH.MANHANVIEN = NV.MANHANVIEN);

-- CÂU 20:Những nhân viên nào của công ty có lương cơ bản cao nhất?

SELECT HO, TEN FROM dbo.NHANVIEN 
WHERE LUONGCOBAN = (SELECT MAX(LUONGCOBAN) FROM dbo.NHANVIEN);

-- CÂU 20: Tổng số tiền mà khách hàng phải trả cho mỗi đơn đặt hàng là bao nhiêu? 
SELECT KH.TENKHACHHANG,CTDH.SOHOADON ,TONGTIEN= SUM(CTDH.SOLUONG*CTDH.GIABAN - CTDH.MUCGIAMGIA) FROM  dbo.KHACHHANG KH 
JOIN dbo.DONDATHANG DDH ON DDH.MAKHACHHANG = KH.MAKHACHHANG
JOIN dbo.CHITIETDATHANG  CTDH ON CTDH.SOHOADON = DDH.SOHOADON
GROUP BY KH.TENKHACHHANG,CTDH.SOHOADON
GO
-- CÂU 21: Trong nm 2019, những mặt hàng nào chỉ được đặt mua đúng một lần.

CREATE PROC SP_KTMATHANGMUA1LAN
AS
BEGIN
	SELECT MH.TENHANG FROM dbo.MATHANG MH 
	JOIN dbo.CHITIETDATHANG CTDH ON CTDH.MAHANG = MH.MAHANG
	JOIN dbo.DONDATHANG DDH ON DDH.SOHOADON = CTDH.SOHOADON
	WHERE YEAR(DDH.NGAYDATHANG) = 2019
	GROUP BY MH.TENHANG
	HAVING COUNT(CTDH.MAHANG) =1
END
GO

EXEC [dbo].[SP_KTMATHANGMUA1LAN]
-- CÂU 22:Hãy cho biết mỗi một khách hàng đã phải bỏ ra bao nhiêu tiền để đặt mua hàng Của công ty?
GO
ALTER FUNCTION FN_TIETRA()
RETURNS TABLE
AS
RETURN 
(
	SELECT KH.TENKHACHHANG ,TONGTIEN= SUM(CTDH.SOLUONG*CTDH.GIABAN - CTDH.MUCGIAMGIA) FROM  dbo.KHACHHANG KH 
	JOIN dbo.DONDATHANG DDH ON DDH.MAKHACHHANG = KH.MAKHACHHANG
	JOIN dbo.CHITIETDATHANG  CTDH ON CTDH.SOHOADON = DDH.SOHOADON
	GROUP BY KH.TENKHACHHANG
)
GO

SELECT * FROM dbo.FN_TIETRA()
GO
-- CÂU 23:	Mỗi một nhân viên của công ty đã lập bao nhiêu đơn đặt hàng (nếu nhân viên chưa hề lập một hoá đơn nào thì cho kết quả là 0)
CREATE PROC SP_SODONDATCUANHANVIEN
AS
BEGIN
	 
	SELECT NV.MANHANVIEN, NV.HO, NV.TEN,COUNT(SOHOADON) FROM dbo.NHANVIEN NV
	LEFT JOIN dbo.DONDATHANG DDH ON DDH.MANHANVIEN = NV.MANHANVIEN
	GROUP BY NV.MANHANVIEN, NV.HO, NV.TEN
END

GO

 EXEC SP_SODONDATCUANHANVIEN
 GO
 
 -- CÂU 24: Cho biết tổng số tiền hàng mà cửa hàng thu được trong mỗi tháng của năm 2003(thời được gian tính theo ngày đặt hàng).
 ALTER FUNCTION FN_SOTIENTHUTRONG1THANG()
 RETURNS TABLE 
 AS 
 RETURN 
 (
	SELECT MONTH(DDH.NGAYDATHANG) THANG, TONTIEN=SUM(CTDH.GIABAN*CTDH.SOLUONG -CTDH.MUCGIAMGIA) FROM dbo.CHITIETDATHANG CTDH
	JOIN dbo.DONDATHANG DDH ON DDH.SOHOADON = CTDH.SOHOADON
	WHERE YEAR(DDH.NGAYDATHANG) = 2019
	GROUP BY MONTH(DDH.NGAYDATHANG)
 )

GO
SELECT * FROM [dbo].[FN_SOTIENTHUTRONG1THANG]();

-- CÂU 25: Hãy cho biết tổng số tiền lãi mà công ty thu được từ mỗi mặt hàng trong năm 2003.
GO

CREATE PROC SP_TIENLAI
AS
BEGIN
	SELECT MH.mahang,tenhang,
	SUM(CTDH.soluong*giaban-CTDH.soluong*giaban*mucgiamgia/100)-
	SUM(CTDH.soluong*giahang)
	FROM (dondathang DDH INNER JOIN chitietdathang CTDH
	ON DDH.sohoadon = CTDH.sohoadon) INNER JOIN mathang MH
	ON CTDH.mahang=MH.mahang
	WHERE YEAR(ngaydathang)=2019
	GROUP BY MH.mahang,tenhang
END
GO
EXEC [dbo].[SP_TIENLAI]
GO

-- CÂU 26:TÍNH TỔNG SỐ HÀNG CẢU MỖI MẠT HÀNG MÀ CÔNG TY ĐÃ CÓ

ALTER VIEW vw_tongsohang 
AS	
SELECT MH.mahang,tenhang,MH.soluong +
	CASE
	WHEN SUM(CTDH.soluong) IS NULL THEN 0
	ELSE SUM(CTDH.soluong)
	END AS tongsoluong
FROM mathang MH LEFT JOIN chitietdathang CTDH
ON MH.mahang=CTDH.mahang
GROUP BY MH.mahang,tenhang,MH.soluong

GO
 SELECT * FROM vw_tongsohang 
GO

 --CÂU 27: Nhân viên nào của công ty bán được số lượng hàng nhiều nhất và số lượng hàng bán được của những nhân viên này là bao nhiêu?

SELECT nv.manhanvien,ho,ten,sum(soluong) soluong
FROM nhanvien nv JOIN dondathang ddh
ON nv.manhanvien=ddh.manhanvien JOIN chitietdathang ctdh
ON ddh.sohoadon = ctdh.sohoadon
GROUP BY nv.manhanvien,ho,ten
HAVING sum(soluong) >= ALL(SELECT sum(soluong)
FROM nhanvien nv JOIN dondathang ddh
ON nv.manhanvien=ddh.manhanvien JOIN chitietdathang ctdh
ON ddh.sohoadon=ctdh.sohoadon
GROUP BY nv.manhanvien,ho,ten)

GO
 --Câu 28: đơn đạt hàng nào có số lượng đạt hàng ít nhất
 
SELECT ddh.sohoadon,SUM(soluong) 
FROM dondathang ddh  JOIN chitietdathang ctdh
ON ddh.sohoadon = ctdh.sohoadon
GROUP BY ddh.sohoadon
HAVING sum(soluong)<=ALL(SELECT sum(soluong)
FROM dondathang ddh JOIN chitietdathang ctdh
ON ddh.sohoadon=ctdh.sohoadon
GROUP BY ddh.sohoadon)

